export type NumberOptions = {
    precision: number;
    thousandth: boolean;
    pretty?: boolean;
    reserve?: boolean;
    raw?: boolean;
    symbol?: string;
};
export declare const parseDate: (date: any, format: any) => any;
export declare const parseNumber: (num: any, options?: NumberOptions) => any;
export declare const prettyNumber: (num: any) => any;
export declare const checkOpera: (engine: any, browser: any) => void;
export declare const checkWebkit: (engine: any, browser: any, ua: any) => void;
export declare const checkHTML: (engine: any, browser: any) => void;
export declare const checkGecko: (engine: any, browser: any, ua: any) => void;
export declare const checkMSIE: (engine: any, browser: any) => void;
export declare const checkWindows: (sys: any, ua: any) => void;
export declare const checkMobile: (sys: any, ua: any) => void;
export declare const checkIOS: (sys: any, ua: any) => void;
export declare const checkAndroid: (sys: any, ua: any) => void;
export declare const checkGame: (sys: any, ua: any) => void;
