/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MtIcon {
        "name": string;
    }
}
declare global {
    interface HTMLMtIconElement extends Components.MtIcon, HTMLStencilElement {
    }
    var HTMLMtIconElement: {
        prototype: HTMLMtIconElement;
        new (): HTMLMtIconElement;
    };
    interface HTMLElementTagNameMap {
        "mt-icon": HTMLMtIconElement;
    }
}
declare namespace LocalJSX {
    interface MtIcon {
        "name"?: string;
    }
    interface IntrinsicElements {
        "mt-icon": MtIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mt-icon": LocalJSX.MtIcon & JSXBase.HTMLAttributes<HTMLMtIconElement>;
        }
    }
}
