/* Automatically generated by @mate-ui 'script/transfer.mjs' */
import MtIconElement from './icon'

class MtIcondCaret extends MtIconElement {
  constructor() {
    super(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><path fill="currentColor" d="m512 128 288 320H224l288-320zM224 576h576L512 896 224 576z"/></svg>`)
  }
}

export default MtIcondCaret

function install() {
  if (window.customElements.get('mt-icon-d-caret')) return
  window.customElements.define('mt-icon-d-caret', MtIcondCaret)
}

export { install as registerComponent }